# sinatra:
#   build: sinatra
#   ports:
#     - 9292:9292
#   volumes:
#     - "$PWD/sinatra:/application"
#   docker-compose 1.4 doesn't support fluentd and gelf log drivers
#   PR https://github.com/docker/compose/pull/1878
#   log_driver: gelf
#   log_opt:
#     address: 'udp://docker.local:12201'
fluentd:
  image: fluent/fluentd:latest
  ports:
    - 24224:24224
  volumes:
    - "$PWD/fluentd:/fluentd/etc"
  environment:
    - FLUENTD_CONF=fluent.docker.conf
    # Set verbose output
    - FLUENTD_OPT=-v

